---
cart:
  note:
  attributes: {}
  original_total_price: 0
  total_price: 0
  total_discount: 0
  total_weight: 0.0
  item_count: 0
  items: []
  requires_shipping: false
  currency: CAD
  items_subtotal_price: 0
  cart_level_discount_applications: []
canonical_url: https://shop1.shopify.storefront-renderer-6tjv.derek-stride.us.spin.dev/products/lightweight-rubber-bottle
current_page: 1
handle: lightweight-rubber-bottle
powered_by_link: <a target="_blank" rel="nofollow" href="https://www.shopify.com?utm_campaign=poweredby&amp;utm_medium=shopify&amp;utm_source=onlinestore">Powered
  by Shopify</a>
template: product
product:
  id: 1
  title: Lightweight Rubber Bottle
  handle: lightweight-rubber-bottle
  description:
  published_at: '2022-05-30T08:18:03-04:00'
  created_at: '2022-05-30T08:18:03-04:00'
  vendor: Brown and Sons
  type: Beauty
  tags: []
  price: 8799
  price_min: 8799
  price_max: 15399
  available: true
  price_varies: true
  compare_at_price:
  compare_at_price_min: 0
  compare_at_price_max: 0
  compare_at_price_varies: false
  variants:
  - id: 1
    title: Aerodynamic Rubber Car
    option1: Aerodynamic Rubber Car
    option2:
    option3:
    sku: ''
    requires_shipping: true
    taxable: true
    featured_image:
    available: true
    name: Lightweight Rubber Bottle - Aerodynamic Rubber Car
    public_title: Aerodynamic Rubber Car
    options:
    - Aerodynamic Rubber Car
    price: 8799
    weight: 8900
    compare_at_price:
    inventory_management: shopify
    barcode:
  - id: 2
    title: Fantastic Leather Pants
    option1: Fantastic Leather Pants
    option2:
    option3:
    sku: ''
    requires_shipping: true
    taxable: true
    featured_image:
    available: true
    name: Lightweight Rubber Bottle - Fantastic Leather Pants
    public_title: Fantastic Leather Pants
    options:
    - Fantastic Leather Pants
    price: 15399
    weight: 8000
    compare_at_price:
    inventory_management: shopify
    barcode:
  images: []
  featured_image:
  options:
  - Color or something
  content:
page_title: Lightweight Rubber Bottle
